drop database bases2;

create database bases2;

use bases2;

DROP TABLE TEMPORAL;
DROP TABLE POBLACION
DROP TABLE POBLACION_RIESGO
DROP TABLE PAIS_ESTADISTICA
DROP TABLE CASOS
DROP TABLE MUERTES
DROP TABLE PRUEBA
DROP TABLE TIPO_PRUEBA
DROP TABLE VACUNACION
DROP TABLE POBLACION_ADMISIONES
DROP TABLE POBLACION_PACIENTES
DROP TABLE PAIS;
DROP TABLE CONTINENTE;


CREATE TABLE TEMPORAL(
	ISO_CODE										VARCHAR(50),
	CONTINENT										VARCHAR(50),
	LOCATIONN										VARCHAR(50),
	DATEE											VARCHAR(50),
	TOTAL_CASES										VARCHAR(50),
	NEW_CASES										VARCHAR(50),
	NEW_CASES_SMOOTHED								VARCHAR(50),
	TOTAL_DEATHS									VARCHAR(50),
	NEW_DEATHS										VARCHAR(50),
	NEW_DEATHS_SMOOTHED								VARCHAR(50),
	TOTAL_CASES_PER_MILLION							VARCHAR(50),
	NEW_CASES_PER_MILLION							VARCHAR(50),
	NEW_CASES_SMOOTHED_PER_MILLION					VARCHAR(50),
	TOTAL_DEATHS_PER_MILLION						VARCHAR(50),
	NEW_DEATHS_PER_MILLION							VARCHAR(50),
	NEW_DEATHS_SMOOTHED_PER_MILLION					VARCHAR(50),
	REPRODUCTION_RATE								VARCHAR(50),
	ICU_PATIENTS									VARCHAR(50),
	ICU_PATIENTS_PER_MILLION						VARCHAR(50),
	HOSP_PATIENTS									VARCHAR(50),
	HOSP_PATIENTS_PER_MILLION						VARCHAR(50),
	WEEKLY_ICU_ADMISSIONS							VARCHAR(50),
	WEEKLY_ICU_ADMISSIONS_PER_MILLION				VARCHAR(50),
	WEEKLY_HOSP_ADMISSIONS							VARCHAR(50),
	WEEKLY_HOSP_ADMISSIONS_PER_MILLION				VARCHAR(50),
	NEW_TESTS										VARCHAR(50),
	TOTAL_TESTS										VARCHAR(50),
	TOTAL_TESTS_PER_THOUSAND						VARCHAR(50),
	NEW_TESTS_PER_THOUSAND							VARCHAR(50),
	NEW_TESTS_SMOOTHED								VARCHAR(50),
	NEW_TESTS_SMOOTHED_PER_THOUSAND					VARCHAR(50),
	POSITIVE_RATE									VARCHAR(50),
	TESTS_PER_CASE									VARCHAR(50),
	TEST_UNITS										VARCHAR(50),
	TOTAL_VACCINATIONS								VARCHAR(50),
	PEOPLE_VACCINATED								VARCHAR(50),
	PEOPLE_FULLY_VACCINATED							VARCHAR(50),
	NEW_VACCINATIONS								VARCHAR(50),
	NEW_VACCINATIONS_SMOOTHED						VARCHAR(50),
	TOTAL_VACCINATIONS_PER_HUNDRED					VARCHAR(50),
	PEOPLE_VACCINATED_PER_HUNDRED					VARCHAR(50),
	PEOPLE_FULLY_VACCINATED_PER_HUNDRED				VARCHAR(50),
	NEW_VACCINATIONS_SMOOTHED_PER_MILLION			VARCHAR(50),
	STRINGENCY_INDEX								VARCHAR(50),
	POPULATIONN										VARCHAR(50),
	POPULATION_DENSITY								VARCHAR(50),
	MEDIAN_AGE										VARCHAR(50),
	AGED_65_OLDER									VARCHAR(50),
	AGED_70_OLDER									VARCHAR(50),
	GDP_PER_CAPITA									VARCHAR(50),
	EXTREME_POVERTY									VARCHAR(50),
	CARDIOVASC_DEATH_RATE							VARCHAR(50),
	DIABETES_PREVALENCE								VARCHAR(50),
	FEMALE_SMOKERS									VARCHAR(50),
	MALE_SMOKERS									VARCHAR(50),
	HANDWASHING_FACILITIES							VARCHAR(50),
	HOSPITAL_DEBS_PER_THOUSAND						VARCHAR(50),
	LIFE_EXPECTANCY									VARCHAR(50),
	HUMAN_DEVELOPMENT_INDEX							VARCHAR(50)
);

SELECT * FROM TEMPORAL;


CREATE TABLE CONTINENTE(
	ID_CONTINENTE		INT NOT NULL PRIMARY KEY IDENTITY( 1 , 1 ),
	CONTINENT			VARCHAR(250)	NOT NULL
);


CREATE TABLE PAIS(
	ID_PAIS			INT NOT NULL PRIMARY KEY IDENTITY( 1 , 1 ),
	ISO_CODE		VARCHAR(250),
	LOCATIONN		VARCHAR(250),
	ID_CONTINENTE	INT					NOT NULL,
	FOREIGN KEY (ID_CONTINENTE) REFERENCES CONTINENTE(ID_CONTINENTE)
);

SELECT * FROM CONTINENTE;
SELECT * FROM PAIS;


CREATE TABLE POBLACION(
	ID_REGISTRO				INT NOT NULL PRIMARY KEY IDENTITY( 1 , 1 ),
	ID_PAIS					INT				NOT NULL,
	DATEE					DATE,
	POPULATIONN				NUMERIC(18,5),
	POPULATION_DENSITY		NUMERIC(18,5),
	MEDIAN_AGE				NUMERIC(18,5),
	HANDWASHING_FACILITIES	NUMERIC(18,5),
	FEMALE_SMOKERS			NUMERIC(18,5),
	MALE_SMOKERS			NUMERIC(18,5),
	FOREIGN KEY (ID_PAIS) REFERENCES PAIS(ID_PAIS)
);
SELECT * FROM POBLACION;

CREATE TABLE POBLACION_RIESGO(
	ID_REGISTRO				INT NOT NULL PRIMARY KEY IDENTITY( 1 , 1 ),
	ID_PAIS					INT		NOT NULL,
	DATEE					DATE,
	AGED_65_OLDER			NUMERIC(18,5)	,
	AGED_70_OLDER			NUMERIC(18,5)	,
	EXTREME_POVERTY			NUMERIC(18,5)	,
	DIABETES_PREVALENCE		NUMERIC(18,5)	,
	FOREIGN KEY (ID_PAIS) REFERENCES PAIS(ID_PAIS)
);

SELECT * FROM POBLACION_RIESGO;

CREATE TABLE PAIS_ESTADISTICA(
	ID_REGISTRO				INT NOT NULL PRIMARY KEY IDENTITY( 1 , 1 ),
	ID_PAIS					INT				NOT NULL,
	DATEE					DATE		,
	LIFE_EXPECTANCY			NUMERIC(18,5)	,
	HUMAN_DEVELOPMENT_INDEX	NUMERIC(18,5)	,
	REPRODUCTION_RATE		NUMERIC(18,5)	,
	STRINGENCY_INDEX		NUMERIC(18,5)	,
	GDP_PER_CAPITA			NUMERIC(18,5)	,
	FOREIGN KEY (ID_PAIS) REFERENCES PAIS(ID_PAIS)
);
SELECT * FROM PAIS_ESTADISTICA;

CREATE TABLE CASOS(
	ID_REGISTRO				INT NOT NULL PRIMARY KEY IDENTITY( 1 , 1 ),
	ID_PAIS				INT				NOT NULL,
	DATEE							DATE		,
	TOTAL_CASES						NUMERIC(18,5)	,
	NEW_CASES						NUMERIC(18,5)	,
	NEW_CASES_SMOOTHED				NUMERIC(18,5)	,
	TOTAL_CASES_PER_MILLION			NUMERIC(18,5)	,
	NEW_CASES_PER_MILLION			NUMERIC(18,5)	,
	NEW_CASES_SMOOTHED_PER_MILLION	NUMERIC(18,5)	,
	POSITIVE_RATE					NUMERIC(18,5)	,
	FOREIGN KEY (ID_PAIS) REFERENCES PAIS(ID_PAIS)
);
SELECT * FROM CASOS;

CREATE TABLE MUERTES(
	ID_REGISTRO				INT NOT NULL PRIMARY KEY IDENTITY( 1 , 1 ),
	ID_PAIS					INT				NOT NULL,
	DATEE							DATE		,
	TOTAL_DEATHS					NUMERIC(18,5)	,
	NEW_DEATHS						NUMERIC(18,5)	,
	NEW_DEATHS_SMOOTHED				NUMERIC(18,5)	,
	TOTAL_DEATHS_PER_MILLION		NUMERIC(18,5)	,
	NEW_DEATHS_PER_MILLION			NUMERIC(18,5)	,
	NEW_DEATHS_SMOOTHED_PER_MILLION	NUMERIC(18,5)	,
	CARDIOVASC_DEATH_RATE			NUMERIC(18,5)	,
	FOREIGN KEY (ID_PAIS) REFERENCES PAIS(ID_PAIS)
);
SELECT * FROM MUERTES;


CREATE TABLE TIPO_PRUEBA(
	ID_TIPO				INT NOT NULL PRIMARY KEY IDENTITY( 1 , 1 ),
	TEST_UNITS										VARCHAR(50)
);
SELECT * FROM TIPO_PRUEBA;


CREATE TABLE PRUEBA(
	ID_REGISTRO				INT NOT NULL PRIMARY KEY IDENTITY( 1 , 1 ),
	ID_PAIS					INT				NOT NULL,
	DATEE							DATE		,
	TOTAL_TESTS						NUMERIC(18,5)	,
	NEW_TESTS						NUMERIC(18,5)	,
	TOTAL_TESTS_PER_THOUSAND		NUMERIC(18,5)	,
	NEW_TESTS_PER_THOUSAND			NUMERIC(18,5)	,
	NEW_TESTS_SMOOTHED				NUMERIC(18,5)	,
	NEW_TESTS_SMOOTHED_PER_THOUSAND	NUMERIC(18,5)	,
	TESTS_PER_CASE					NUMERIC(18,5)	,
	ID_TIPO							INT				,
	FOREIGN KEY (ID_PAIS) REFERENCES PAIS(ID_PAIS),
	FOREIGN KEY (ID_TIPO) REFERENCES TIPO_PRUEBA(ID_TIPO)
);
SELECT * FROM PRUEBA;



CREATE TABLE VACUNACION(
	ID_REGISTRO				INT NOT NULL PRIMARY KEY IDENTITY( 1 , 1 ),
	ID_PAIS					INT				NOT NULL,
	DATEE							DATE		,
	TOTAL_VACCINATIONS					NUMERIC(18,5)	,
	PEOPLE_FULLY_VACCINATED				NUMERIC(18,5)	,
	NEW_VACCINATIONS					NUMERIC(18,5)	,
	NEW_VACCINATIONS_SMOOTHED			NUMERIC(18,5)	,
	TOTAL_VACCINATIONS_PER_HUNDRED		NUMERIC(18,5)	,
	PEOPLE_VACCINATED_PER_HUNDRED		NUMERIC(18,5)	,
	PEOPLE_FULLY_VACCINATED_PER_HUNDRED	NUMERIC(18,5)	,
	NEW_VACCINATIONS_SMOOTHED_PER_MILLION	NUMERIC(18,5)	,
	FOREIGN KEY (ID_PAIS) REFERENCES PAIS(ID_PAIS)
);
SELECT * FROM VACUNACION;



CREATE TABLE POBLACION_ADMISIONES(
	ID_REGISTRO				INT NOT NULL PRIMARY KEY IDENTITY( 1 , 1 ),
	ID_PAIS					INT				NOT NULL,
	DATEE								DATE,
	WEEKLY_ICU_ADMISSIONS				NUMERIC(18,5)	,
	WEEKLY_ICU_ADMISSIONS_PER_MILLION	NUMERIC(18,5)	,
	WEEKLY_HOSP_ADMISSIONS				NUMERIC(18,5)	,
	WEEKLY_HOSP_ADMISSIONS_PER_MILLION	NUMERIC(18,5)	,
	FOREIGN KEY (ID_PAIS) REFERENCES PAIS(ID_PAIS)
);
SELECT * FROM POBLACION_ADMISIONES;



CREATE TABLE POBLACION_PACIENTES(
	ID_REGISTRO				INT NOT NULL PRIMARY KEY IDENTITY( 1 , 1 ),
	ID_PAIS					INT				NOT NULL,
	DATEE						DATE,
	ICU_PATIENTS				NUMERIC(18,5)	,
	ICU_PATIENTS_PER_MILLION	NUMERIC(18,5)	,
	HOSP_PATIENTS				NUMERIC(18,5)	,
	HOSP_PATIENTS_PER_MILLION	NUMERIC(18,5)	,
	HOSPITAL_DEBS_PER_THOUSAND	NUMERIC(18,5)	,
	FOREIGN KEY (ID_PAIS) REFERENCES PAIS(ID_PAIS)
);
SELECT * FROM POBLACION_PACIENTES;